local T = dofile(TESTS_DIR .. '/helpers.lua')
local web = require('config.diff_review.web')

T.describe('diff_review/web.lua', function()
  T.it('renders a self-contained page with the app mount point', function()
    local html = web.render({})
    T.contains(html, '<!doctype html>')
    T.contains(html, 'id="app"')
    T.eq(html:find('__TITLE__', 1, true), nil)
  end)

  T.it('fetches the diff and comment APIs and polls the version', function()
    local html = web.render({})
    T.contains(html, '/api/diff')
    T.contains(html, '/api/comments')
    T.contains(html, '/api/session')
    T.contains(html, '/__version')
    T.contains(html, '/api/comments/reply')
  end)

  T.it('ships the unified/side-by-side toggle persisted in localStorage', function()
    local html = web.render({})
    T.contains(html, 'id="modebtn"')
    T.contains(html, 'diffReviewMode')
    T.contains(html, 'renderHunkSplit')
    T.contains(html, 'renderHunkUnified')
  end)

  T.it('ships the all/unstaged/staged view toggle (comments only in all)', function()
    local html = web.render({})
    T.contains(html, 'id="viewseg"')
    T.contains(html, 'data-view="staged"')
    T.contains(html, 'diffReviewView')
    T.contains(html, 'function commentable')
    T.contains(html, '/api/diff?view=')
  end)

  T.it('ships a changed-file tree sidebar', function()
    local html = web.render({})
    T.contains(html, 'id="tree"')
    T.contains(html, 'function buildTree')
    T.contains(html, 'function renderTree')
    T.contains(html, 'scrollIntoView')
  end)

  T.it('loads syntax highlighting from vendored highlight.js', function()
    local html = web.render({})
    T.contains(html, '/__vendor/highlight.min.js')
    T.contains(html, '/__vendor/highlight-theme.css')
    T.contains(html, 'hljs.highlight')
  end)

  T.it('supports range (multi-line) comments and generated-file collapse', function()
    local html = web.render({})
    T.contains(html, 'function isGenerated')      -- lock/generated auto-collapse
    T.contains(html, 'shouldCollapse')
    T.contains(html, 'line_end')                  -- range comment payload
    T.contains(html, 'range-sel')
  end)

  T.it('has a delete-all-comments button guarded by a confirm dialog', function()
    local html = web.render({})
    T.contains(html, 'id="clearbtn"')
    T.contains(html, '/api/comments/clear')
    T.contains(html, 'window.confirm')
  end)

  T.it('puts the repo basename in the title', function()
    local html = web.render({ repo_root = '/home/me/project' })
    T.contains(html, '<title>Diff Review · project</title>')
  end)

  T.it('escapes html in the title', function()
    local html = web.render({ repo_root = '/tmp/a<b' })
    T.contains(html, 'a&lt;b')
  end)
end)

T.summary()
