local T = dofile(TESTS_DIR .. '/helpers.lua')
local GP = dofile(TESTS_DIR .. '/git_panel_helpers.lua')

T.describe('git_panel Stash panel', function()
  T.it('Space applies the selected stash, keeping it in the stash list', function()
    local dir = T.tmp_git_repo(function(d)
      T.write_file(d .. '/a.txt', { 'a' })
      GP.git(d, { 'add', '.' })
      GP.git(d, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'seed' })
    end)
    T.write_file(dir .. '/a.txt', { 'a', 'stashed change' })
    GP.git(dir, { 'stash', 'push', '-m', 'my stash' })
    T.eq(vim.fn.readfile(dir .. '/a.txt'), { 'a' }) -- 待避後は元に戻っている

    GP.open(dir, false)
    GP.press('4') -- Stashパネル
    vim.wait(300)
    local left = GP.left_win()
    T.contains(table.concat(GP.lines(left), '\n'), 'my stash')
    GP.press('<Space>')
    T.wait_until(function()
      local ok, content = pcall(vim.fn.readfile, dir .. '/a.txt')
      return ok and vim.deep_equal(content, { 'a', 'stashed change' })
    end)
    T.eq(vim.fn.readfile(dir .. '/a.txt'), { 'a', 'stashed change' })
    T.eq(#vim.split(vim.trim(GP.git(dir, { 'stash', 'list' }).stdout), '\n'), 1, 'apply should keep the stash entry')

    GP.close()
    T.rmrf(dir)
  end)

  T.it('g pops the selected stash, removing it from the list', function()
    local dir = T.tmp_git_repo(function(d)
      T.write_file(d .. '/a.txt', { 'a' })
      GP.git(d, { 'add', '.' })
      GP.git(d, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'seed' })
    end)
    T.write_file(dir .. '/a.txt', { 'a', 'pop me' })
    GP.git(dir, { 'stash', 'push', '-m', 'to pop' })

    GP.open(dir, false)
    GP.press('4')
    vim.wait(300)
    GP.press('g')
    T.wait_until(function() return vim.trim(GP.git(dir, { 'stash', 'list' }).stdout) == '' end)
    T.eq(vim.trim(GP.git(dir, { 'stash', 'list' }).stdout), '')
    T.eq(vim.fn.readfile(dir .. '/a.txt'), { 'a', 'pop me' })

    GP.close()
    T.rmrf(dir)
  end)

  T.it('d drops the selected stash after confirmation', function()
    local dir = T.tmp_git_repo(function(d)
      T.write_file(d .. '/a.txt', { 'a' })
      GP.git(d, { 'add', '.' })
      GP.git(d, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'seed' })
    end)
    T.write_file(dir .. '/a.txt', { 'a', 'drop me' })
    GP.git(dir, { 'stash', 'push', '-m', 'to drop' })

    GP.open(dir, false)
    GP.press('4')
    vim.wait(300)
    GP.press('d')
    vim.wait(80)
    GP.press_modal('y')
    T.wait_until(function() return vim.trim(GP.git(dir, { 'stash', 'list' }).stdout) == '' end)
    T.eq(vim.trim(GP.git(dir, { 'stash', 'list' }).stdout), '')
    -- dropは適用しない(working treeは変わらない)
    T.eq(vim.fn.readfile(dir .. '/a.txt'), { 'a' })

    GP.close()
    T.rmrf(dir)
  end)

  T.it('n creates a new branch from the selected stash', function()
    local dir = T.tmp_git_repo(function(d)
      T.write_file(d .. '/a.txt', { 'a' })
      GP.git(d, { 'add', '.' })
      GP.git(d, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'seed' })
    end)
    T.write_file(dir .. '/a.txt', { 'a', 'branchable' })
    GP.git(dir, { 'stash', 'push', '-m', 'for branch' })

    GP.open(dir, false)
    GP.press('4')
    vim.wait(300)
    GP.press('n')
    vim.wait(80)
    GP.press_modal('ifrom-stash')
    GP.press_modal('<CR>')
    T.wait_until(function() return GP.git(dir, { 'rev-parse', '--verify', 'from-stash' }).code == 0 end)
    T.eq(GP.git(dir, { 'rev-parse', '--verify', 'from-stash' }).code, 0)

    GP.close()
    T.rmrf(dir)
  end)
end)

T.summary()
