-- branches.luaの残りキー(c/-/F/M/r/R/f/u)のテスト。branches_spec.luaはSpace/n/d/Dしか
-- 検証していなかった。checkout_by_name(c)のfuzzy絞り込み自体はui.suggest_inputとして
-- git_panel_ui_spec.luaで検証済みなので、ここでは配線(選んだ結果が実際にcheckoutされるか)
-- だけをデフォルト選択(絞り込み無し)で確認する

local T = dofile(TESTS_DIR .. '/helpers.lua')
local GP = dofile(TESTS_DIR .. '/git_panel_helpers.lua')

T.describe('git_panel Branches panel: checkout-by-name/force/merge/rebase/rename/ff/upstream', function()
  T.it('c opens a ref picker; <CR> with no typed filter checks out the top (alphabetically first) candidate', function()
    local dir = T.tmp_git_repo()
    GP.git(dir, { 'branch', 'aaa-target' }) -- refs/heads/配下ではmainより辞書順で先頭になる
    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    GP.press('c')
    T.wait_until(function() return GP.win_by_title('チェックアウト') ~= nil end, 2000)
    GP.press_modal('<CR>')
    T.wait_until(function()
      return vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout) == 'aaa-target'
    end)
    T.eq(vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout), 'aaa-target')

    GP.close()
    T.rmrf(dir)
  end)

  T.it('c offers to create a new branch when the typed ref does not exist', function()
    local dir = T.tmp_git_repo()
    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    GP.press('c')
    T.wait_until(function() return GP.win_by_title('チェックアウト') ~= nil end, 2000)
    GP.press_modal('ibrand-new-branch')
    vim.api.nvim_exec_autocmds('TextChangedI', { buffer = vim.api.nvim_get_current_buf() })
    GP.press_modal('<CR>')
    T.wait_until(function() return GP.win_by_title('確認') ~= nil end, 2000)
    GP.press_modal('y')
    T.wait_until(function()
      return vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout) == 'brand-new-branch'
    end)
    T.eq(vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout), 'brand-new-branch')

    GP.close()
    T.rmrf(dir)
  end)

  T.it('- checks out the previously checked-out branch (like `git checkout -`)', function()
    local dir = T.tmp_git_repo()
    GP.git(dir, { 'branch', 'feature' })
    GP.git(dir, { 'checkout', '-q', 'feature' })
    GP.git(dir, { 'checkout', '-q', 'main' })
    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    GP.press('-')
    T.wait_until(function()
      return vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout) == 'feature'
    end)
    T.eq(vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout), 'feature')

    GP.close()
    T.rmrf(dir)
  end)

  T.it('F force-checks-out a branch, discarding dirty working-tree changes', function()
    local dir = T.tmp_git_repo(function(d)
      T.write_file(d .. '/a.txt', { 'a' })
      GP.git(d, { 'add', '.' })
      GP.git(d, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'seed' })
    end)
    GP.git(dir, { 'branch', 'feature' })
    T.write_file(dir .. '/a.txt', { 'a', 'dirty, would block a plain checkout' })
    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    local left = GP.left_win()
    GP.goto_row(left, GP.find_row(left, 'feature'))
    GP.press('F')
    vim.wait(80)
    GP.press_modal('y')
    T.wait_until(function()
      return vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout) == 'feature'
    end)
    T.eq(vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout), 'feature')
    T.eq(vim.trim(GP.git(dir, { 'status', '--porcelain' }).stdout), '', 'dirty change should have been discarded')

    GP.close()
    T.rmrf(dir)
  end)

  T.it('M merges the branch under the cursor into the current branch', function()
    local dir = T.tmp_git_repo()
    GP.git(dir, { 'branch', 'feature' })
    GP.git(dir, { 'checkout', '-q', 'feature' })
    T.write_file(dir .. '/feature.txt', { 'x' })
    GP.git(dir, { 'add', '.' })
    GP.git(dir, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'feature work' })
    GP.git(dir, { 'checkout', '-q', 'main' })

    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    local left = GP.left_win()
    GP.goto_row(left, GP.find_row(left, 'feature'))
    GP.press('M')
    vim.wait(80)
    GP.press_modal('y')
    T.wait_until(function() return vim.fn.filereadable(dir .. '/feature.txt') == 1 end)
    T.eq(vim.fn.filereadable(dir .. '/feature.txt'), 1)
    T.eq(vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout), 'main')

    GP.close()
    T.rmrf(dir)
  end)

  T.it('r rebases the current branch onto the branch under the cursor', function()
    local dir = T.tmp_git_repo()
    T.write_file(dir .. '/base.txt', { 'b' })
    GP.git(dir, { 'add', '.' })
    GP.git(dir, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'base commit' })
    GP.git(dir, { 'branch', 'feature', 'HEAD~1' }) -- baseの前から分岐させる
    GP.git(dir, { 'checkout', '-q', 'feature' })
    T.write_file(dir .. '/feature.txt', { 'f' })
    GP.git(dir, { 'add', '.' })
    GP.git(dir, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'feature commit' })
    T.eq(vim.fn.filereadable(dir .. '/base.txt'), 0, 'sanity: feature must not yet contain base.txt')

    GP.open(dir, false)
    GP.press('3')
    T.wait_until(function() return GP.find_row(GP.left_win(), 'main') ~= nil end)
    local left = GP.left_win()
    GP.goto_row(left, GP.find_row(left, 'main'))
    GP.press('r')
    vim.wait(80)
    GP.press_modal('y')
    T.wait_until(function()
      return vim.fn.filereadable(dir .. '/base.txt') == 1
        and GP.git(dir, { 'log', '--format=%s', 'feature' }).stdout:find('base commit', 1, true) ~= nil
    end)
    T.eq(vim.fn.filereadable(dir .. '/base.txt'), 1, 'feature should now contain the base commit from main')
    T.eq(vim.trim(GP.git(dir, { 'log', '--format=%s', 'feature' }).stdout):find('base commit') ~= nil, true)

    GP.close()
    T.rmrf(dir)
  end)

  T.it('R renames the branch under the cursor', function()
    local dir = T.tmp_git_repo()
    GP.git(dir, { 'branch', 'old-name' })
    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    local left = GP.left_win()
    GP.goto_row(left, GP.find_row(left, 'old-name'))
    -- input()はデフォルト値(現在の名前)を入れた状態で開くため、<C-u>で
    -- クリアしてから入力しないと末尾に追記されてしまう
    GP.press('R<C-u>new-name<CR>')
    T.wait_until(function() return GP.git(dir, { 'rev-parse', '--verify', 'new-name' }).code == 0 end)
    T.eq(GP.git(dir, { 'rev-parse', '--verify', 'new-name' }).code, 0)
    T.ok(GP.git(dir, { 'rev-parse', '--verify', 'old-name' }).code ~= 0, 'old name should be gone')

    GP.close()
    T.rmrf(dir)
  end)

  T.it('f fast-forwards a branch that is behind its upstream, without checking it out', function()
    local remote = vim.fn.tempname()
    vim.fn.mkdir(remote, 'p')
    GP.git(remote, { 'init', '-q', '--bare', '-b', 'main' })
    local dir = vim.fn.tempname()
    vim.system({ 'git', 'clone', '-q', remote, dir }):wait()
    T.write_file(dir .. '/a.txt', { 'a' })
    GP.git(dir, { 'add', '.' })
    GP.git(dir, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'seed' })
    GP.git(dir, { 'push', '-u', 'origin', 'main' })

    local other = vim.fn.tempname()
    vim.system({ 'git', 'clone', '-q', remote, other }):wait()
    T.write_file(other .. '/b.txt', { 'b' })
    GP.git(other, { 'add', '.' })
    GP.git(other, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'from other' })
    GP.git(other, { 'push', 'origin', 'main' })
    GP.git(dir, { 'fetch', 'origin' }) -- behindだと認識させる(f自体はfetchしない)

    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    local left = GP.left_win()
    GP.goto_row(left, GP.find_row(left, 'main'))
    GP.press('f')
    T.wait_until(function() return vim.fn.filereadable(dir .. '/b.txt') == 1 end)
    T.eq(vim.fn.filereadable(dir .. '/b.txt'), 1)
    T.eq(vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'HEAD' }).stdout), 'main',
      'fast-forward should not switch away from the current branch')

    GP.close()
    T.rmrf(dir); T.rmrf(other); T.rmrf(remote)
  end)

  T.it('f warns instead of erroring when the branch has no upstream', function()
    local dir = T.tmp_git_repo()
    GP.git(dir, { 'branch', 'no-upstream' })
    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    local left = GP.left_win()
    GP.goto_row(left, GP.find_row(left, 'no-upstream'))
    GP.press('f')
    vim.wait(100)
    -- クラッシュせず、パネルはそのまま操作可能であること
    T.ok(GP.left_win() ~= nil)

    GP.close()
    T.rmrf(dir)
  end)

  T.it('u sets the upstream for the branch under the cursor to a given remote', function()
    local remote = vim.fn.tempname()
    vim.fn.mkdir(remote, 'p')
    GP.git(remote, { 'init', '-q', '--bare', '-b', 'main' })
    local dir = vim.fn.tempname()
    vim.system({ 'git', 'clone', '-q', remote, dir }):wait()
    T.write_file(dir .. '/a.txt', { 'a' })
    GP.git(dir, { 'add', '.' })
    GP.git(dir, { '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-qm', 'seed' })
    GP.git(dir, { 'push', 'origin', 'main' }) -- -uなし: upstream未設定のまま
    GP.git(dir, { 'branch', 'feature' })
    GP.git(dir, { 'push', 'origin', 'feature' })

    GP.open(dir, false)
    GP.press('3')
    vim.wait(200)
    local left = GP.left_win()
    GP.goto_row(left, GP.find_row(left, 'feature'))
    GP.press('u<CR>') -- デフォルト値'origin'のままEnter
    T.wait_until(function()
      return GP.git(dir, { 'rev-parse', '--abbrev-ref', 'feature@{u}' }).code == 0
    end)
    T.eq(vim.trim(GP.git(dir, { 'rev-parse', '--abbrev-ref', 'feature@{u}' }).stdout), 'origin/feature')

    GP.close()
    T.rmrf(dir); T.rmrf(remote)
  end)
end)

T.summary()
