local T = dofile(TESTS_DIR .. '/helpers.lua')
local ss = require('config.start_screen')

T.describe('start_screen', function()
  T.it('shows a non-editable scratch buffer (not an editable [No Name])', function()
    vim.cmd('silent! only')
    vim.cmd('enew')
    local buf = ss.show()
    T.eq(vim.bo[buf].buftype, 'nofile')
    T.eq(vim.bo[buf].modifiable, false) -- 入力できない＝未保存にならない
    T.eq(vim.bo[buf].buflisted, false)
    T.eq(vim.bo[buf].swapfile, false)
    T.eq(vim.bo[buf].filetype, 'startscreen')
    T.eq(vim.api.nvim_win_get_buf(0), buf)
  end)

  T.it('returns to the start screen after the last file buffer is closed', function()
    vim.cmd('silent! only')
    vim.cmd('%bwipeout!')
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, 'p')
    T.write_file(dir .. '/f.txt', { 'hello' })
    vim.cmd('edit ' .. vim.fn.fnameescape(dir .. '/f.txt'))
    T.eq(vim.bo.filetype, '')
    vim.cmd('bdelete ' .. vim.api.nvim_get_current_buf())
    vim.wait(100)
    T.eq(vim.bo.filetype, 'startscreen') -- 最後のファイルを閉じたらスタート画面へ
    T.rmrf(dir)
  end)

  T.it('does NOT return to the start screen while another file is still open', function()
    vim.cmd('silent! only')
    vim.cmd('%bwipeout!')
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, 'p')
    T.write_file(dir .. '/a.txt', { 'a' })
    T.write_file(dir .. '/b.txt', { 'b' })
    vim.cmd('edit ' .. vim.fn.fnameescape(dir .. '/a.txt'))
    vim.cmd('edit ' .. vim.fn.fnameescape(dir .. '/b.txt'))
    vim.cmd('bdelete ' .. vim.api.nvim_get_current_buf()) -- b を閉じる（a が残る）
    vim.wait(100)
    T.ok(vim.bo.filetype ~= 'startscreen', 'still on a file, not the start screen')
    vim.cmd('%bwipeout!')
    T.rmrf(dir)
  end)

  T.it('is excluded from the tabline and from the unsaved-changes check', function()
    vim.cmd('silent! only')
    vim.cmd('enew')
    ss.show()
    require('config.tabline')
    T.ok(_G._tabline():find('startscreen', 1, true) == nil, 'not shown in tabline')
    -- 編集不可なので modified にできず、未保存判定にも出ない
    local qc = require('config.quit_confirm')
    T.eq(#qc._unsaved_names(), 0)
  end)
end)

T.summary()
