require("config.options")
require("config.tabline")
require("config.yazi")
require("config.lazygit")
require("config.git_blame")
require("config.hlchunk")
require("config.term_utils")
require("config.terminal")
